---
#
# copy.nic.file.yml - Copy virtual NIC FILE
#


- name: COPY VIRTUAL NIC FILE
  hosts: load_balancer 
  tasks:
  - name: Copy Virtual NIC File
    ansible.builtin.copy:
      src: /home/ansible/nic_files/
      dest: /home/arcsight/
      owner: root
      group: root
      mode: '0644'
