---
#
# copy.arcsight.connector.8.2.yml - Copy host file to servers
#

- name: Copy Connector Files
  hosts: connector  
  tasks:
  - name: Copy Connector Files
    ansible.builtin.copy:
      src: /home/ansible/connector_files/8.2/ 
      dest: /home/arcsight
      owner: root
      group: root
      mode: '0755'
