---
#
# copy.license.arcmc.yml - Copy host file to servers
#
# Author: Richard Hamilton <Richard.Mailton@Microfocus.com>

- name: copy.license.arcmc.yml
  hosts: arc_mc 
  tasks:
  - name: Copy Host File
    ansible.builtin.copy:
      src: /home/ansible/ansible-files/arcmc-license.dat
      dest: /root
      owner: root
      group: root
      mode: '0644'
