---
#
# copy.arcsight.lb.141.yml - Copy ESM 7.5 Files to server
#

- name: Copy Arcsight Loadbalancer Files
  hosts: load_balancer
  tasks:
  - name: Copy Loadblancer Files
    ansible.builtin.copy:
      src: /home/ansible/loadbalancer_files/1.4.1/ 
      dest: /home/arcsight 
      owner: root
      group: root
      mode: '0755'
