---
#
# fetch.linux.netconfig.yml - Copy host file to servers
#

- name: NIC File
  hosts: all 
  tasks:
  - name: Fetch NIC Config File
    ansible.builtin.fetch:
      src: /etc/sysconfig/network-scripts/ifcfg-ens192
      dest: /home/ansible/ansible_files/ifcfg-ens192-{{ inventory_hostname }}
