---
#
# package.install.syslog.server.yml - Install the expect package
# 


- name: package.install.syslog.server.yml
  hosts: syslog_nodes 
  tasks:
    - name: Install Syslog
      yum:
         name: "rsyslog"
         state: latest
      
