---
#
# os.configure.arcsight.connector.yml - Install Arcsight Logger 7.2 on Cent/RHEL 7/8
#
- name: os.configure.arcsight.connector.yml
  hosts: connector 
  tasks:
  - name: Configure YUM proxy
    ansible.builtin.lineinfile:
      path: /etc/yum.conf
      line: proxy=http://web-proxy:8080
      create: yes
  - name: Install Base Packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - unzip
      - zip
      - fontconfig
      - dejavu-sans-fonts
      - yum-utils
      - audit
  - name: Update OS Packages
    yum:
      name: '*'
      state: latest
  - name: Create Arcsight Group
    ansible.builtin.group:
      name: arcsight
      state: present
      gid: 750
  - name: Create Arcsight User
    ansible.builtin.user:
      name: arcsight
      password: '_your_hash_password_'
      state: present
      uid: 1500
      group: arcsight
