---
#
# os.configure.arcsight.arcmc.yml - Install Arcsight Logger 7.2 on Cent/RHEL 7/8
#
#
# Notes: Update the password prior to use 
#        Management ports still need to be configured 
# 
- name: os.configure.arcsight.arcmc.yml
  hosts: [arcmc] 
  tasks:
  - name: Configure YUM proxy
    ansible.builtin.lineinfile:
      path: /etc/yum.conf
      line: proxy=http://web-proxy:8080
      create: yes
  - name: Install Base Packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - unzip
      - zip
      - fontconfig
      - dejavu-sans-fonts
      - yum-utils
      - expect
  - name: Update OS Packages
    yum:
      name: '*'
      state: latest
  - name: Create Arcsight Group
    ansible.builtin.group:
      name: arcsight
      state: present
      gid: 750
  - name: Create Arcsight User
    ansible.builtin.user:
      name: arcsight
      password: '_your_password_hashed_'
      state: present
      uid: 1500
      group: arcsight
  - name: Add HTTPS to Firewall
    ansible.posix.firewalld:
      service: https
      permanent: yes
      state: enabled
  - name: Firewall Setup Additional ports
    ansible.posix.firewalld:
      port: "{{ item.port}}/{{item.proto}}"
      permanent: yes
      state: enabled
    with_items:
      - {port: "9000", proto: "tcp"}
      - {port: "9001", proto: "tcp"}
      - {port: "9002", proto: "tcp"}
      - {port: "9003", proto: "tcp"}
      - {port: "9004", proto: "tcp"}
  - name: Restart firewalld
    service:
      name: firewalld.service
      state: restarted
  - name: Copy Host File
    ansible.builtin.copy:
      src: /home/ansible/ansible-files/arcmc-license.dat
      dest: /root
      owner: root
      group: root
      mode: '0644'
  - name: Set UTF-8 Environment Variables
    blockinfile:
      path: /root/.bashrc
      block: "{{ lookup('file','/home/ansible/ansible-files/arcmc.bashrc') }}"
      backup: yes
  - name: Set Limits
    blockinfile:
      path: /etc/security/limits.conf
      block: "{{ lookup('file','/home/ansible/ansible-files/limits.conf') }}"
 
