---
- hosts: all
  tasks:
  - debug:
      msg:
      - "ansible_distribution {{ hostvars[inventory_hostname].ansible_distribution }}"
      - "host {{ ansible_hostname }}"
      - "major version {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
      - "version {{ hostvars[inventory_hostname].ansible_distribution_version }}"
