---
#
# os.linux.reboot.yml - Reboot multiple LINUX servers
#                       Make sure to limit to single server or group
#               
- name: os.linux.reboot.yml
  hosts: all
  become: yes
  tasks:
  - name: Reboot Servers
    reboot:
      reboot_timeout: 120 
